#pragma once

namespace RenderSys {
#include <resources/Shaders/ShaderMaterial.h>

enum MaterialFeatures // bitset
{
    HAS_DIFFUSE_MAP = GLSL_HAS_DIFFUSE_MAP,
    HAS_NORMAL_MAP = GLSL_HAS_NORMAL_MAP,
    HAS_ROUGHNESS_MAP = GLSL_HAS_ROUGHNESS_MAP,
    HAS_METALLIC_MAP = GLSL_HAS_METALLIC_MAP,
    HAS_ROUGHNESS_METALLIC_MAP = GLSL_HAS_ROUGHNESS_METALLIC_MAP,
    HAS_EMISSIVE_COLOR = GLSL_HAS_EMISSIVE_COLOR,
    HAS_EMISSIVE_MAP = GLSL_HAS_EMISSIVE_MAP
};

}
